config/routes.rb
Rails.application.routes.draw do
  apipie

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  resources :passive_workouts

  resources :passive_activities

  resources :passive_sleeps

  resources :effective_time_intervals

  resources :passive_data_points

  resources :pre_defined_cards

  resources :reviews

  resources :rewards

  resources :reminders

  resources :scorecards

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => 'my_devise/registrations',
                                                                                                                :omniauth_callbacks => "omniauth_callbacks", :sessions => 'my_devise/sessions', :passwords => 'users/passwords', :invitations => 'my_devise/invitations'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 'welcome#index'

  get 'welcome/index'

  get 'superusers/index'

  resources :superusers do
    get 'export_moods'
    get 'export_sleeps'
    get 'export_self_cares'
    get 'export_journals'
  end

  resources :pros, only: [:index]

  resources :supporters, only: [:index] do
    post '/invite' => 'supporters#invite', :on => :collection
  end

  match 'moods/cancel' => 'moods#cancel', :via => :get

  match 'sleeps/cancel' => 'sleeps#cancel', :via => :get

  match 'self_cares/cancel' => 'self_cares#cancel', :via => :get

  match 'journals/cancel' => 'journals#cancel', :via => :get

  resources :moods do
    get "delete"
  end

  resources :sleeps do
    get "delete"
  end

  resources :self_cares do
    get "delete"
  end

  resources :journals do
    get "delete"
  end

  get "/update_capture" => 'capture#update_capture', as: 'update_capture'

  get "/app_constants" => 'application#app_constants', as: 'app_constants'

  get "/feature_flags" => 'feature_flags#feature_flags', as: 'feature_flags'

  resources :conversations, :path => 'cards_stack', only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, :path => 'cards', only: [:new, :create] do
    get "random_draw", :on => :collection
  end

  resources :users, :path => 'thrivers' do
    post "migrate_from_thrivetracker", :on => :collection
    post "migrate_from_thrivetracker_admin", :on => :collection
    post "request_password_reset_from_thrivetracker", :on => :collection
    resources :moods
    resources :sleeps
    resources :self_cares
    resources :journals
  end

  resources :connections, :controller => 'friendships', :except => [:show, :edit] do
    get "thrivers", :on => :collection
    get "supporters", :on => :collection
    get "patients", :on => :collection
    get "providers", :on => :collection
  end

  resources :devices

  flipper_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints flipper_constraint do
    mount Flipper::UI.app($flipper) => '/flipper'
  end

  get '/start' => 'high_voltage/pages#show', id: 'pricing'

  require 'api_constraints'

  namespace :api, defaults: {format: :json} do #, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        post '/registrations' => 'registrations#create'
        put '/registrations' => 'registrations#update'
        post '/sessions' => 'sessions#create'
        delete '/sessions' => 'sessions#destroy'
        post '/passwords' => 'passwords#create'
      end

      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only => [:create, :update, :destroy]
      resources :passwords, :only => [:create, :update]
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  acts_as_token_authentication_handler_for User

  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  after_action :verify_authorized

  respond_to :html, :json

  def show
    authorize :conversation, :show?
  end

  def index
    authorize :conversation, :index?
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 9)

    @cards = []
    @conversations.each do |conversation|
      @cards << {
        :category => conversation.last_message.subject,
        :message => conversation.last_message.body,
        :sender_first_name => conversation.last_message.sender.first_name,
        :sender_last_name => conversation.last_message.sender.last_name,
        :sent_time => (conversation.last_message.created_at.to_datetime).strftime("%Y-%m-%d %H:%M:%S %z")
      }
    end

    respond_to do |format|
      format.html
      format.json { render :json => {:cards => @cards}, status: 200 }
    end
  end

  def destroy
    authorize :conversation, :destroy?
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    authorize :conversation, :restore?
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    authorize :conversation, :empty_trash?
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    authorize :conversation, :mark_as_read?
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox", "sent", "trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                    data: {confirm: 'Are you sure?'} %>

        <% if conversation.is_unread?(current_user) %>
            <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                        class: 'btn btn-xs btn-info', method: :post %>
        <% end %>
    <% end %>
  </div>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)
    </small>
  </p>
</li>

app/views/conversations/index.html.erb
<center><h2>T-Max Cards</h2></center>

<br>

<div class="container">
  <%= will_paginate %>
  <% @conversations.each_slice(3) do |conversations| %>
      <div class="row">
        <% conversations.each do |conversation| %>
            <div class="col-md-4">
              <div class="card shadow-z-1">
                <div class="card-height-indicator"></div>
                <div class="card-content">
                  <div class="card-body" id="t-max-card-message">
                    <center>
                      <%= conversation.last_message.body %>
                    </center>
                  </div>
                  <footer class="card-footer">
                    <center>
                      <p>
                        <%= conversation.last_message.sender.first_name + " " + conversation.last_message.sender.last_name %>
                        <br>
                        <small>
                          <span class="text-muted"><%= conversation.last_message.created_at.strftime("%B %-d, %Y") %></span>
                        </small>
                      </p>
                    </center>
                  </footer>
                </div>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/conversations/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
          <% message = receipt.message %>

          <%= message.sender.name %>
          (<%= I18n.l message.created_at, format: :long_am_pm %>):
          <%= message.body %>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div class="form-group">
      <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something to reply...', required: true %>
    </div>
    <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>