config/routes.rb
Rails.application.routes.draw do
  apipie

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  resources :passive_workouts

  resources :passive_activities

  resources :passive_sleeps

  resources :effective_time_intervals

  resources :passive_data_points

  resources :pre_defined_cards

  resources :reviews

  resources :rewards

  resources :reminders

  resources :scorecards

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => 'my_devise/registrations',
                                                                                                                :omniauth_callbacks => "omniauth_callbacks", :sessions => 'my_devise/sessions', :passwords => 'users/passwords', :invitations => 'my_devise/invitations'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 'welcome#index'

  get 'welcome/index'

  get 'superusers/index'

  resources :superusers do
    get 'export_moods'
    get 'export_sleeps'
    get 'export_self_cares'
    get 'export_journals'
  end

  resources :pros, only: [:index]

  resources :supporters, only: [:index] do
    post '/invite' => 'supporters#invite', :on => :collection
  end

  match 'moods/cancel' => 'moods#cancel', :via => :get

  match 'sleeps/cancel' => 'sleeps#cancel', :via => :get

  match 'self_cares/cancel' => 'self_cares#cancel', :via => :get

  match 'journals/cancel' => 'journals#cancel', :via => :get

  resources :moods do
    get "delete"
  end

  resources :sleeps do
    get "delete"
  end

  resources :self_cares do
    get "delete"
  end

  resources :journals do
    get "delete"
  end

  get "/update_capture" => 'capture#update_capture', as: 'update_capture'

  get "/app_constants" => 'application#app_constants', as: 'app_constants'

  get "/feature_flags" => 'feature_flags#feature_flags', as: 'feature_flags'

  resources :conversations, :path => 'cards_stack', only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, :path => 'cards', only: [:new, :create] do
    get "random_draw", :on => :collection
  end

  resources :users, :path => 'thrivers' do
    post "migrate_from_thrivetracker", :on => :collection
    post "migrate_from_thrivetracker_admin", :on => :collection
    post "request_password_reset_from_thrivetracker", :on => :collection
    resources :moods
    resources :sleeps
    resources :self_cares
    resources :journals
  end

  resources :connections, :controller => 'friendships', :except => [:show, :edit] do
    get "thrivers", :on => :collection
    get "supporters", :on => :collection
    get "patients", :on => :collection
    get "providers", :on => :collection
  end

  resources :devices

  flipper_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints flipper_constraint do
    mount Flipper::UI.app($flipper) => '/flipper'
  end

  get '/start' => 'high_voltage/pages#show', id: 'pricing'

  require 'api_constraints'

  namespace :api, defaults: {format: :json} do #, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        post '/registrations' => 'registrations#create'
        put '/registrations' => 'registrations#update'
        post '/sessions' => 'sessions#create'
        delete '/sessions' => 'sessions#destroy'
        post '/passwords' => 'passwords#create'
      end

      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only => [:create, :update, :destroy]
      resources :passwords, :only => [:create, :update]
    end
  end

end

app/models/passive_data_point.rb
class PassiveDataPoint < ActiveRecord::Base
  belongs_to :user
  has_many :effective_time_intervals, :dependent => :destroy
  has_many :passive_sleeps, :dependent => :destroy
  has_many :passive_activities, :dependent => :destroy
  has_many :passive_workouts, :dependent => :destroy

  accepts_nested_attributes_for :effective_time_intervals, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :passive_sleeps, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :passive_activities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :passive_workouts, reject_if: :all_blank, allow_destroy: true

  #validates_presence_of :source_uuid, :creation_date_time, :schema_namespace, :schema_name, :schema_version

  scope :by_source_uuid, -> source_uuid { where(:source_uuid => source_uuid) }
  scope :by_external_uuid, -> external_uuid { where(:external_uuid => external_uuid) }
end

app/controllers/passive_data_points_controller.rb
class PassiveDataPointsController < ApplicationController
  resource_description do
    short 'Passive Data Point Entries'
    desc <<-EOS
      == Long description
        Passive Data Point Entries include:
          Required Fields:
            user_id: integer
            source_uuid: string
            creation_date_time: datetime
            schema_namespace: string
            schema_name: string
            schema_version: string
          Optional Fields:
            was_user_entered: boolean
            timezone: string
            external_uuid: string
            effective_date_time: datetime

      ===Sample JSON Output:
          {
            "passive_data_point": {
              "id": 1,
              "user_id": 3,
              "was_user_entered": true,
              "timezone": "EST",
              "source_uuid": "abc1234",
              "external_uuid": "xyz7890",
              "creation_date_time": "2016-02-15 08:35:00 -0500",
              "schema_namespace": "test_namespace",
              "schema_name": "test_name",
              "schema_version": "test_version",
              "effective_date_time": "2016-02-15 09:34:00 -0500"
            }
          }
    EOS
    api_base_url ""
    formats ['html', 'json']
  end

  def_param_group :passive_data_points_data do
    param :passive_data_point, Hash, :desc => "Passive Data Point", :required => false do
      param :source_uuid, :undef, :desc => "Source Identification of Passive Data Point [String]", :required => true
      param :creation_date_time, :undef, :desc => "Creation Date as defined from Source [Timestamp]", :required => false
      param :schema_namespace, :undef, :desc => "Schema Namespace [String]", :required => true
      param :schema_name, :undef, :desc => "Schema Name [String]", :required => true
      param :schema_version, :undef, :desc => "Schema Version [String]", :required => true
      param :effective_date_time, :undef, :desc => "Effective Date Time [Timestamp]", :required => false
      param :effective_time_intervals_attributes, :undef, :desc => "Array of Effective Time Intervals [{start_date_time, end_date_time}]", :required => false
    end
  end

  def_param_group :passive_data_points_all do
    param_group :passive_data_points_data
    param :was_user_entered, :undef, :desc => "User Entered Flag [Boolean]", :required => false
    param :timezone, :undef, :desc => "Timezone [String]", :required => false
    param :external_uuid, :undef, :desc => "External Source Identification of Passive Data Point [String]", :required => false
    param_group :passive_sleep
    param_group :passive_activity
    param_group :passive_workout
  end

  def_param_group :passive_sleep do
    param :passive_sleeps_attributes, :undef, :desc => "Array of Passive Sleeps [{passive_data_id, category_type, category_value, value, unit}]", :required => false
  end

  def_param_group :passive_activity do
    param :passive_activities_attributes, :undef, :desc => "Array of Passive Activities [{passive_data_id, activity_type, value, unit, kcal_burned_value, kcal_burned_unit, step_count}]", :required => false
  end

  def_param_group :passive_workout do
    param :passive_workouts_attributes, :undef, :desc => "Array of Passive Workouts [{passive_data_id, workout_type, kcal_burned_value, kcal_burned_unit,distance_value, distance_unit}]", :required => false
  end

  def_param_group :destroy_passive_data_point_data do
    param :id, :number, :desc => "Id of Passive Data Point to Delete [Number]", :required => true
  end

  acts_as_token_authentication_handler_for User

  before_action :set_passive_data_point, only: [:show, :edit, :update, :destroy]

  after_action :verify_authorized, except: [:index]

  respond_to :html, :json

  has_scope :by_source_uuid
  has_scope :by_external_uuid

  # GET /passive_data_points
  # GET /passive_data_points.json
  api! "Show Passive Data Points"

  def index
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      @passive_data_points = apply_scopes(PassiveDataPoint).where(user_id: current_user.id)
      skip_authorization
    elsif @user != nil
      @passive_data_points = apply_scopes(PassiveDataPoint).where(user_id: @user.id)
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    respond_to do |format|
      format.html
      format.json { render :json => @passive_data_points, status: 200 }
    end
  end

  # GET /passive_data_points/1
  # GET /passive_data_points/1.json
  def show
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    respond_to do |format|
      format.html
      format.json { render :json => @passive_data_point, status: 200 }
    end
  end

  # GET /passive_data_points/new
  def new
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    @passive_data_point = PassiveDataPoint.new

    respond_to do |format|
      format.html
      format.json { render :json => @passive_data_point, status: 200 }
    end
  end

  # GET /passive_data_points/1/edit
  def edit
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    respond_to do |format|
      format.html
      format.json { render :json => @passive_data_point, status: 200 }
    end
  end

  # POST /passive_data_points
  # POST /passive_data_points.json
  api! "Create Passive Data Point"
  param_group :passive_data_points_data

  def create
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    @passive_data_point = PassiveDataPoint.new(passive_data_point_params)
    @passive_data_point.user_id = current_user.id

    respond_to do |format|
      if @passive_data_point.save
        track_passive_data_point_created
        flash[:success] = 'Passive Data Point was successfully created.'
        format.html { redirect_to passive_data_points_path }
        format.json { render json: @passive_data_point, status: :created }
      else
        flash[:error] = 'Passive Data Point was not created... Try again???'
        format.html { render :new }
        format.json { render json: @passive_data_points.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passive_data_points/1
  # PATCH/PUT /passive_data_points/1.json
  api! "Update Passive Data Point"
  param_group :passive_data_points_data

  def update
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    respond_to do |format|
      if @passive_data_point.update(passive_data_point_params)
        track_passive_data_point_updated

        flash.now[:success] = 'Passive Data Point was successfully updated.'
        format.html { redirect_to passive_data_points_url, notice: 'Passive Data Point was successfully updated.' }
        format.json { render :json => @passive_data_point, status: :created }
      else
        flash.now[:error] = 'Passive Data Point was not updated... Try again???'
        format.json { render json: @passive_data_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passive_data_points/1
  # DELETE /passive_data_points/1.json
  api! "Delete Passive Data Point"
  param_group :destroy_passive_data_point_data

  def destroy
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @passive_data_points
      end
    end

    respond_to do |format|
      if @passive_data_point.destroy
        track_passive_data_point_deleted
        flash[:success] = 'Passive Data Point was successfully deleted.'
        format.html { redirect_to passive_data_points_path }
        format.json { head :no_content }
      else
        flash[:error] = 'Passive Data Point was not deleted... Try again???'
        format.html { redirect passive_data_points_path }
        format.json { render json: @passive_data_points.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_passive_data_point
      @passive_data_point = PassiveDataPoint.find(params[:id])
    end

    def passive_data_point_params
      params.fetch(:passive_data_point, {}).permit(:user_id, :was_user_entered, :timezone,  :source_uuid, :external_uuid,
                                                   :creation_date_time, :schema_namespace, :schema_name,  :schema_version,
                                                   :effective_date_time,
                                                   effective_time_intervals_attributes: [
                                                     :id,
                                                     :passive_data_point_id,
                                                     :start_date_time,
                                                     :end_date_time,
                                                     :_destroy
                                                   ],
                                                   passive_sleeps_attributes: [
                                                     :id,

app/helpers/passive_data_points_helper.rb
module PassiveDataPointsHelper
end

app/views/passive_data_points/_effective_time_intervals_fields.html.haml
.nested-fields
  .field
    = f.label :start_date_time
    %br
    = f.datetime_select :start_date_time, hide_label: true
  .field
    = f.label :end_date_time
    %br
    = f.datetime_select :end_date_time, hide_label: true
  = link_to_remove_association "Remove Effective Time Interval", f

app/views/passive_data_points/_form.html.haml
= bootstrap_form_for(@passive_data_point) do |f|
  - if @passive_data_point.errors.any?
    #error_explanation
      %h2 = pluralize(@passive_data_point.errors.count, "error") prohibited this passive_data_point from being saved:
      %ul
      = @passive_data_point.errors.full_messages.each do |message|
        %li = message
  .field
    = f.label :was_user_entered
    %br
    = f.text_field :was_user_entered, hide_label: true
  .field
    = f.label :timezone
    %br
    = f.text_field :timezone, hide_label: true
  .field
    = f.label :source_uuid
    %br
    = f.text_field :source_uuid, hide_label: true
  .field
    = f.label :external_uuid
    %br
    = f.text_field :external_uuid, hide_label: true
  .field
    = f.label :creation_date_time
    %br
    = f.datetime_select :creation_date_time, hide_label: true
  .field
    = f.label :schema_namespace
    %br
    = f.text_field :schema_namespace, hide_label: true
  .field
    = f.label :schema_name
    %br
    = f.text_field :schema_name, hide_label: true
  .field
    = f.label :schema_version
    %br
    = f.text_field :schema_version, hide_label: true
  .field
    = f.label :effective_date_time
    %br
    = f.datetime_select :effective_date_time, include_blank: true, hide_label: true
  %h5 Effective Time Intervals
  #effective_time_intervals
    = f.fields_for :effective_time_intervals do |effective_time_interval|
      = render 'effective_time_intervals_fields', f: effective_time_interval
    .links
      = link_to_add_association 'Add Effective Time Interval', f, :effective_time_intervals, :partial => 'effective_time_intervals_fields'
  %br
  %h5 Passive Sleep Entries
  #passive_sleeps
    = f.fields_for :passive_sleeps do |passive_sleep|
      = render 'passive_sleeps_fields', f: passive_sleep
    .links
      = link_to_add_association 'Add Passive Sleep', f, :passive_sleeps, :partial => 'passive_sleeps_fields'
  %br
  %h5 Passive Activity Entries
  #passive_activities
    = f.fields_for :passive_activities do |passive_activity|
      = render 'passive_activities_fields', f: passive_activity
    .links
      = link_to_add_association 'Add Passive Activity', f, :passive_activities, :partial => 'passive_activities_fields'
  %br
  %h5 Passive Workout Entries
  #passive_workouts
    = f.fields_for :passive_workouts do |passive_workout|
      = render 'passive_workouts_fields', f: passive_workout
    .links
      = link_to_add_association 'Add Passive Workout', f, :passive_workouts, :partial => 'passive_workouts_fields'
  %br
  .actions
    = f.submit

app/views/passive_data_points/_passive_activities_fields.html.haml
.nested-fields
  .field
    = f.label :activity_type
    %br
    = f.text_field :activity_type, hide_label: true
  .field
    = f.label :value
    %br
    = f.text_field :value, hide_label: true
  .field
    = f.label :unit
    %br
    = f.text_field :unit, hide_label: true
  .field
    = f.label :kcal_burned_value
    %br
    = f.text_field :kcal_burned_value, hide_label: true
  .field
    = f.label :kcal_burned_unit
    %br
    = f.text_field :kcal_burned_unit, hide_label: true
  .field
    = f.label :step_count
    %br
    = f.text_field :step_count, hide_label: true
  = link_to_remove_association "Remove Passive Activity", f

app/views/passive_data_points/_passive_sleeps_fields.html.haml
.nested-fields
  .field
    = f.label :category_type
    %br
    = f.text_field :category_type, hide_label: true
  .field
    = f.label :category_value
    %br
    = f.text_field :category_value, hide_label: true
  .field
    = f.label :value
    %br
    = f.text_field :value, hide_label: true
  .field
    = f.label :unit
    %br
    = f.text_field :unit, hide_label: true
  = link_to_remove_association "Remove Passive Sleep", f

app/views/passive_data_points/_passive_workouts_fields.html.haml
.nested-fields
  .field
    = f.label :workout_type
    %br
    = f.text_field :workout_type, hide_label: true
  .field
    = f.label :kcal_burned_value
    %br
    = f.text_field :kcal_burned_value, hide_label: true
  .field
    = f.label :kcal_burned_unit
    %br
    = f.text_field :kcal_burned_unit, hide_label: true
  .field
    = f.label :distance_value
    %br
    = f.text_field :distance_value, hide_label: true
  .field
    = f.label :distance_unit
    %br
  .field
    = f.label :duration_value
    %br
    = f.text_field :distance_value, hide_label: true
  .field
    = f.label :duration_unit
    %br
    = f.text_field :distance_unit, hide_label: true
  = link_to_remove_association "Remove Passive Workout", f

app/views/passive_data_points/edit.html.erb
<div class="container">
    <h1>Edit Passive Data Point</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @passive_data_point %> |
    <%= link_to 'Back', passive_data_points_path %>
</div>

app/views/passive_data_points/index.html.erb
<div class="container">
    <h1>Passive Data Points</h1>

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Was user entered</th>
          <th>Timezone</th>
          <th>Source uuid</th>
          <th>External uuid</th>
          <th>Creation date time</th>
          <th>Schema namespace</th>
          <th>Schema name</th>
          <th>Schema version</th>
          <th>Effective date time</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @passive_data_points.each do |passive_data_point| %>
          <tr>
            <td><%= passive_data_point.user_id %></td>
            <td><%= passive_data_point.was_user_entered %></td>
            <td><%= passive_data_point.timezone %></td>
            <td><%= passive_data_point.source_uuid %></td>
            <td><%= passive_data_point.external_uuid %></td>
            <td><%= passive_data_point.creation_date_time %></td>
            <td><%= passive_data_point.schema_namespace %></td>
            <td><%= passive_data_point.schema_name %></td>
            <td><%= passive_data_point.schema_version %></td>
            <td><%= passive_data_point.effective_date_time %></td>
            <td><%= link_to 'Show', passive_data_point %></td>
            <td><%= link_to 'Edit', edit_passive_data_point_path(passive_data_point) %></td>
            <td><%= link_to 'Destroy', passive_data_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Passive data point', new_passive_data_point_path %>
</div>

app/views/passive_data_points/new.html.erb
<div class="container">
    <h1>New Passive Data Point</h1>

    <%= render 'form' %>

    <%= link_to 'Back', passive_data_points_path %>
</div>

app/views/passive_data_points/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>User:</strong>
      <%= @passive_data_point.user_id %>
    </p>

    <p>
      <strong>Was user entered:</strong>
      <%= @passive_data_point.was_user_entered %>
    </p>
    <p>
      <strong>Timezone:</strong>
      <%= @passive_data_point.timezone %>
    </p>
    <p>
      <strong>Source uuid:</strong>
      <%= @passive_data_point.source_uuid %>
    </p>

    <p>
      <strong>External uuid:</strong>
      <%= @passive_data_point.external_uuid %>
    </p>

    <p>
      <strong>Creation date time:</strong>
      <%= @passive_data_point.creation_date_time %>
    </p>

    <p>
      <strong>Schema namespace:</strong>
      <%= @passive_data_point.schema_namespace %>
    </p>

    <p>
      <strong>Schema name:</strong>
      <%= @passive_data_point.schema_name %>
    </p>

    <p>
      <strong>Schema version:</strong>
      <%= @passive_data_point.schema_version %>
    </p>

    <p>
      <strong>Effective date time:</strong>
      <% if @passive_data_point.effective_date_time.nil? %>
          <%= 'NA' %>
      <% else %>
        <%= @passive_data_point.effective_date_time %>
      <% end %>
    </p>

    <p>
      <strong>Effective Time Intervals:</strong>

      <table>
        <thead>
        <tr>
          <th>Id</th>
          <th>Start Date Time</th>
          <th>End Date Time</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @passive_data_point.effective_time_intervals.each do |effective_time_interval| %>
          <tr>
            <td><%= effective_time_interval.id %></td>
            <td><%= effective_time_interval.start_date_time %></td>
            <td><%= effective_time_interval.end_date_time %></td>
            <td><%= link_to 'Show', effective_time_interval %></td>
            <td><%= link_to 'Edit', edit_effective_time_interval_path(effective_time_interval) %></td>
            <td><%= link_to 'Destroy', effective_time_interval, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </p>

    <p>
      <strong>Passive Sleep Entries:</strong>

    <table>
      <thead>
      <tr>
        <th>Id</th>
        <th>Category Type</th>
        <th>Category Value</th>
        <th>Value</th>
        <th>Unit</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @passive_data_point.passive_sleeps.each do |passive_sleep| %>
          <tr>
            <td><%= passive_sleep.id %></td>
            <td><%= passive_sleep.category_type  %></td>
            <td><%= passive_sleep.category_value %></td>
            <td><%= passive_sleep.value  %></td>
            <td><%= passive_sleep.unit %></td>
            <td><%= link_to 'Show', passive_sleep%></td>
            <td><%= link_to 'Edit', edit_passive_sleep_path(passive_sleep) %></td>
            <td><%= link_to 'Destroy', passive_sleep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    </p>

    <p>
      <strong>Passive Activity Entries:</strong>

    <table>
      <thead>
      <tr>
        <th>Id</th>
        <th>Type</th>
        <th>Value</th>
        <th>Unit</th>
        <th>Kcal Burned Value</th>
        <th>Kcal Burned Unit</th>
        <th>Step Count</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @passive_data_point.passive_activities.each do |passive_activity| %>
        <tr>
          <td><%= passive_activity.id %></td>
          <td><%= passive_activity.activity_type  %></td>
          <td><%= passive_activity.value %></td>
          <td><%= passive_activity.unit %></td>
          <td><%= passive_activity.kcal_burned_value %></td>
          <td><%= passive_activity.kcal_burned_unit %></td>
          <td><%= passive_activity.step_count %></td>
          <td><%= link_to 'Show', passive_activity%></td>
          <td><%= link_to 'Edit', edit_passive_activity_path(passive_activity) %></td>
          <td><%= link_to 'Destroy', passive_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </p>

  <p>
    <strong>Passive Workout Entries:</strong>

  <table>
    <thead>
    <tr>
      <th>Id</th>
      <th>Type</th>
      <th>Kcal Burned Value</th>
      <th>Kcal Burned Unit</th>
      <th>Distance Value</th>
      <th>Distance Unit</th>
      <th>Duration Value</th>
      <th>Duration Unit</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @passive_data_point.passive_workouts.each do |passive_workout| %>
        <tr>
          <td><%= passive_workout.id %></td>
          <td><%= passive_workout.workout_type  %></td>
          <td><%= passive_workout.kcal_burned_value %></td>
          <td><%= passive_workout.kcal_burned_unit %></td>
          <td><%= passive_workout.distance_value %></td>
          <td><%= passive_workout.distance_unit %></td>
          <td><%= passive_workout.duration_value %></td>
          <td><%= passive_workout.duration_unit %></td>
          <td><%= link_to 'Show', passive_workout%></td>
          <td><%= link_to 'Edit', edit_passive_workout_path(passive_workout) %></td>
          <td><%= link_to 'Destroy', passive_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  </p>
    <%= link_to 'Edit', edit_passive_data_point_path(@passive_data_point) %> |
    <%= link_to 'Back', passive_data_points_path %>
</div>