config/routes.rb
Rails.application.routes.draw do
  apipie

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  resources :passive_workouts

  resources :passive_activities

  resources :passive_sleeps

  resources :effective_time_intervals

  resources :passive_data_points

  resources :pre_defined_cards

  resources :reviews

  resources :rewards

  resources :reminders

  resources :scorecards

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => 'my_devise/registrations',
                                                                                                                :omniauth_callbacks => "omniauth_callbacks", :sessions => 'my_devise/sessions', :passwords => 'users/passwords', :invitations => 'my_devise/invitations'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 'welcome#index'

  get 'welcome/index'

  get 'superusers/index'

  resources :superusers do
    get 'export_moods'
    get 'export_sleeps'
    get 'export_self_cares'
    get 'export_journals'
  end

  resources :pros, only: [:index]

  resources :supporters, only: [:index] do
    post '/invite' => 'supporters#invite', :on => :collection
  end

  match 'moods/cancel' => 'moods#cancel', :via => :get

  match 'sleeps/cancel' => 'sleeps#cancel', :via => :get

  match 'self_cares/cancel' => 'self_cares#cancel', :via => :get

  match 'journals/cancel' => 'journals#cancel', :via => :get

  resources :moods do
    get "delete"
  end

  resources :sleeps do
    get "delete"
  end

  resources :self_cares do
    get "delete"
  end

  resources :journals do
    get "delete"
  end

  get "/update_capture" => 'capture#update_capture', as: 'update_capture'

  get "/app_constants" => 'application#app_constants', as: 'app_constants'

  get "/feature_flags" => 'feature_flags#feature_flags', as: 'feature_flags'

  resources :conversations, :path => 'cards_stack', only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, :path => 'cards', only: [:new, :create] do
    get "random_draw", :on => :collection
  end

  resources :users, :path => 'thrivers' do
    post "migrate_from_thrivetracker", :on => :collection
    post "migrate_from_thrivetracker_admin", :on => :collection
    post "request_password_reset_from_thrivetracker", :on => :collection
    resources :moods
    resources :sleeps
    resources :self_cares
    resources :journals
  end

  resources :connections, :controller => 'friendships', :except => [:show, :edit] do
    get "thrivers", :on => :collection
    get "supporters", :on => :collection
    get "patients", :on => :collection
    get "providers", :on => :collection
  end

  resources :devices

  flipper_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints flipper_constraint do
    mount Flipper::UI.app($flipper) => '/flipper'
  end

  get '/start' => 'high_voltage/pages#show', id: 'pricing'

  require 'api_constraints'

  namespace :api, defaults: {format: :json} do #, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        post '/registrations' => 'registrations#create'
        put '/registrations' => 'registrations#update'
        post '/sessions' => 'sessions#create'
        delete '/sessions' => 'sessions#destroy'
        post '/passwords' => 'passwords#create'
      end

      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only => [:create, :update, :destroy]
      resources :passwords, :only => [:create, :update]
    end
  end

end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :start_time, :finish_time
  validates :time, numericality: {only_integer: true}
  validates :quality, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 4}

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |sleep|
        csv << sleep.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/sleeps_controller.rb
class SleepsController < ApplicationController
  resource_description do
    short 'Sleep Entries'
    desc <<-EOS
      == Long description
        Sleep Entries include:
          Start Time
          Finish Time
          Quality
          Time

      ===Sample JSON Output:
          {
            "sleeps": [
              {
                "id": 2657,
                "start_time": "2014-10-27 00:30:00 -0400",
                "finish_time": "2014-10-27 06:00:00 -0400",
                "quality": 2,
                "time": 5,
                "created_at": "2014-10-27 06:02:09 -0400",
                "updated_at": "2014-10-27 06:02:09 -0400",
                "user_id": 24
              }
            ]
          }
    EOS
    api_base_url ""
    formats ['html', 'json']
  end

  def_param_group :sleeps_data do
    param :sleep, Hash, :desc => "Sleep", :required => false do
      param :start_time, :undef, :desc => "Sleep Start Time [DateTime(UTC)]", :required => false
      param :finish_time, :undef, :desc => "Sleep Finish Time [DateTime(UTC)]", :required => false
      param :quality, :number, :desc => "[['Broken', 1], ['Light', 2], ['Normal', 3], ['Deep',4]]", :required => true
    end
  end

  def_param_group :sleeps_all do
    param_group :sleeps_data
  end

  def_param_group :destroy_sleeps_data do
    param :id, :number, :desc => "Id of Sleep Entry to Delete [Number]", :required => true
  end

  acts_as_token_authentication_handler_for User

  before_action :set_sleep, only: [:show, :edit, :update, :destroy]
  before_action :set_lookback_period, only: [:index]
  before_action :authenticate_user!

  after_filter :verify_authorized, except: [:index]
  #after_filter :verify_policy_scoped, only: [:index]

  respond_to :html, :js, :json

  # GET /sleeps
  # GET /sleeps.json
  api! "Show Sleep Entries"

  def index
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      @sleeps = Sleep.where(user_id: current_user.id)
      skip_authorization
    elsif @user != nil
      @sleeps = Sleep.where(user_id: @user.id)
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    #@sleeps = policy_scope(@sleeps)

    respond_to do |format|
      format.html
      format.js
      format.json { render :json => @sleeps, status: 200 }
    end
  end

  # GET /sleeps/1
  # GET /sleeps/1.json
  def show
    authorize! :manage, Sleep
    authorize! :read, Sleep

    respond_to do |format|
      format.js { render :nothing => true }
      format.json { render :json => @sleep, status: 200 }
    end
  end

  # GET /sleeps/new
  def new
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    @sleep= Sleep.new

    respond_to do |format|
      format.html { render :nothing => true }
      format.js
      format.json { render :json => @sleep, status: 200 }
    end
  end

  # GET /sleeps/1/edit
  def edit
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    respond_to do |format|
      format.html { render :nothing => true }
      format.js
      format.json { render :json => @sleep, status: 200 }
    end
  end

  # POST /sleeps
  # POST /sleeps.json
  api! "Create Sleep Entry"
  param_group :sleeps_data

  def create
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    @sleep = Sleep.new(sleep_params)
    @sleep.user_id = current_user.id
    @sleep.time = (@sleep.finish_time.to_i - @sleep.start_time.to_i) / 3600

    #days_sleeps = Sleep.where(user_id: current_user.id, finish_time: (@sleep.finish_time.to_time.in_time_zone.at_beginning_of_day..@sleep.finish_time.to_time.in_time_zone.end_of_day))
    days_sleeps = Sleep.where(user_id: current_user.id, finish_time: ((@sleep.finish_time.to_time.in_time_zone.- 24.hours)..@sleep.finish_time.to_time.in_time_zone))

    respond_to do |format|
      if days_sleeps.count < MAX_SLEEP_ENTRIES
        if @sleep.save
          track_sleep_created
          current_user.scorecard.update_scorecard('sleeps', Time.zone.now)
          flash.now[:success] = 'Sleep Entry was successfully tracked.'
          format.js
          format.json { render :json => @sleep, status: :created }
        else
          flash.now[:error] = 'Sleep Entry was not tracked... Try again???'
          format.js { render json: @sleep.errors, status: :unprocessable_entity }
          format.json { render json: @sleep.errors, status: :unprocessable_entity }
        end
      else
        flash.now[:warning] = 'Sleep Entry was not tracked.  Daily Sleep Entry Limit Reached.'
        format.js
        format.json { render json: 'Sleep Entry was not tracked.  Daily Sleep Entry Limit Reached.', status: 400 }
      end
    end
  end

  # PATCH/PUT /sleeps/1
  # PATCH/PUT /sleeps/1.json
  api! "Update Sleep Entry"
  param_group :sleeps_all

  def update
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    finish_time = sleep_params[:finish_time].to_datetime
    #days_sleeps = Sleep.where(user_id: current_user.id, finish_time: (finish_time.in_time_zone.at_beginning_of_day..finish_time.in_time_zone.end_of_day))
    days_sleeps = Sleep.where(user_id: current_user.id, finish_time: ((finish_time.to_time.in_time_zone.- 24.hours)..finish_time.to_time.in_time_zone))

    respond_to do |format|
      if @sleep.update(sleep_params)
        @sleep.time = (@sleep.finish_time.to_i - @sleep.start_time.to_i) / 3600
        @sleep.save
        track_sleep_updated

        flash.now[:success] = 'Sleep Entry was successfully updated.'
        format.js { render status: 200 }
        format.json { render :json => @sleep, status: :created }
      else
        flash.now[:error] = 'Sleep Entry was not updated.  Daily Sleep Entry Limit Reached.'
        format.js
        format.json { render json: 'Sleep Entry was not updated.  Daily Sleep Entry Limit Reached.', status: 400 }
      end
    end
  end

  def delete
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    @sleep = Sleep.find(params[:sleep_id])
  end

  # DELETE /sleeps/1
  # DELETE /sleeps/1.json
  api! "Delete Sleep Entry"
  param_group :destroy_sleeps_data

  def destroy
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    respond_to do |format|
      if @sleep.destroy
        track_sleep_deleted
        flash[:success] = 'Sleep Entry was successfully deleted.'
        format.html { redirect_to sleeps_path }
        format.js
        format.json { head :no_content }
      else
        flash[:error] = 'Sleep Entry was not deleted... Try again???'
        format.html { redirect sleeps_path }
        format.js
        format.json { render json: @sleeps.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    @user = User.find_by_id(params[:user_id])

    if @user == nil
      skip_authorization
    elsif @user != nil
      if @user.id == current_user.id
        skip_authorization
      else
        authorize @sleeps
      end
    end

    $current_capture_screen = "Sleep"

    respond_to do |format|
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sleep
    @sleep = Sleep.find(params[:id])
  end

  def set_lookback_period
    if params.has_key? :sleep_lookback_period
      @sleep_lookback_period = params[:sleep_lookback_period]
    else
      @sleep_lookback_period = DEFAULT_LOOKBACK_PERIOD
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sleep_params
    params.fetch(:sleep, {}).permit(:start_time, :finish_time, :quality, :sleep_lookback_period)
  end

  def track_sleep_created
    # Track Sleep Creation for Segment.io Analytics
    Analytics.track(
      user_id: current_user.id,
      event: 'Sleep Entry Created',
      properties: {
        sleep_id: @sleep.id,
        start_time: @sleep.start_time,
        finish_time: @sleep.finish_time,
        quality: @sleep.quality,
        sleep_user_id: @sleep.user_id
      }
    )
  end

  def track_sleep_updated
    # Track Sleep Update for Segment.io Analytics
    Analytics.track(
      user_id: current_user.id,
      event: 'Sleep Entry Updated',
      properties: {
        sleep_id: @sleep.id,
        start_time: @sleep.start_time,
        finish_time: @sleep.finish_time,
        quality: @sleep.quality,
        sleep_user_id: @sleep.user_id
      }
    )
  end

  def track_sleep_deleted
    # Track Sleep Deletion for Segment.io Analytics
    Analytics.track(
      user_id: current_user.id,
      event: 'Sleep Entry Deleted',
      properties: {
      }
    )
  end
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/views/sleeps/_delete.html.erb
<div class="modal-header">
  <h3>Delete Sleep Entry</h3>
</div>

<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete this sleep entry?
</div>

<div class="modal-footer">
  <%= link_to "Yes, Delete This Sleep Entry", sleep_path(@sleep), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
</div>

app/views/sleeps/_details.html.erb
<div class="col-sm-12">
  <% if !@sleeps.empty? %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Sleep Entries</h3>
        </div>
        <div class="panel-body">
          <%
             if @sleep_lookback_period == 'week'
               lookback_range = date_range_for('this_week')
             elsif @sleep_lookback_period == 'last_week'
               lookback_range = date_range_for('last_week')
             elsif @sleep_lookback_period == 'month'
               lookback_range = date_range_for('this_month')
             elsif @sleep_lookback_period == 'last_month'
               lookback_range = date_range_for('last_month')
             elsif @sleep_lookback_period == 'year'
               lookback_range = date_range_for('this_year')
             elsif @sleep_lookback_period == 'last_year'
               lookback_range = date_range_for('last_year')
             end

             sleeps_for_lookback_period = @sleeps.where(finish_time: lookback_range)
             sleeps_for_lookback_period = sleeps_for_lookback_period.order('finish_time DESC')

             sleeps_for_lookback_period.each do |sleep| %>

              <% if sleep.user_id == current_user.id || (current_user.is? :superuser) || (current_user.is? :pro) && (current_user.clients.include? sleep.user_id) %>
                  <div class="col-md-4">
                    <h4><%= sleep.finish_time.strftime("%a - %B %e, %Y") %></h4>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <strong>Sleep Start Time:</strong>
                      <%= I18n.l sleep.start_time, format: :long_am_pm %>
                    </p>

                    <p>
                      <strong>Sleep Finish Time:</strong>
                      <%= I18n.l sleep.finish_time, format: :long_am_pm %>
                    </p>

                    <p>
                      <strong>Sleep Quality:</strong>
                      <% if sleep.quality == 1 %>
                          <%= "Broken" %>
                      <% elsif sleep.quality == 2 %>
                          <%= "Light" %>
                      <% elsif sleep.quality == 3 %>
                          <%= "Normal" %>
                      <% elsif sleep.quality == 4 %>
                          <%= "Deep" %>
                      <% end %>
                      (<%= sleep.quality %>)
                    </p>
                  </div>
                  <div class="col-md-4">
                    <%= link_to 'Edit', edit_sleep_path(sleep, modal_enabled: 'true'), remote: true, class: "btn-default btn-xs" %>
                    <%= link_to 'Remove', sleep_delete_path(sleep, modal_enabled: 'true'), class: "btn-danger btn-xs", remote: true, sleep: sleep %>
                  </div>
                  <div class="col-md-12">
                    <hr>
                  </div>
              <% end %>
          <% end %>
        </div>
      </div>
  <% end %>
</div>

app/views/sleeps/_edit.html.erb
<div class="modal-header">
  <h1>Edit Sleep Entry</h1>
</div>

<%= render 'form' %>

app/views/sleeps/_form.html.erb
<%= bootstrap_form_for @sleep, layout: :inline, remote: true do |f| %>
    <div class="modal-body">
      <% if @sleep.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@sleep.errors.count, 'error') %> prohibited this sleep entry from being saved:</h2>
            <ul>
              <% @sleep.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if $capture_date == Time.zone.now.to_date || $capture_date == nil %>
          <%  sleep_entry_day = Time.zone.now.to_date %>
      <% else %>
          <%  sleep_entry_day = $capture_date %>
      <% end %>

      <%
         d = sleep_entry_day.to_date
         t = Time.now
         dt = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, t.zone)
         dt_minus_8 = (dt.to_time - 8.hours).to_datetime
      %>

      <div class="form-group">
        <%= f.label 'Sleep Start Time:' %> <br>
        <%= f.datetime_local_field :start_time, hide_label: true, default: dt_minus_8 %>
        <% #f.datetime_select :start_time, ampm: true, hide_label: true, default: dt_minus_8 %>
      </div>
      <br><br>
      <div class="form-group">
        <%= f.label 'Sleep Finish Time:' %> <br>
        <%= f.datetime_local_field :finish_time, hide_label: true, default: dt_minus_8 %>
        <% #f.datetime_select :finish_time, ampm: true, hide_label: true, default: dt  %>
      </div>
      <br><br>
      <div class="form-group">
        <% if !@sleep.quality.nil? %>
            <% selected_quality = @sleep.quality %>
        <% else %>
            <% selected_quality = 1 %>
        <% end %>
        <%= f.label 'Sleep Quality:' %><br>
        <%= f.select :quality, options_for_select([['Broken', 1], ['Light', 2], ['Normal', 3], ['Deep', 4]], selected_quality), hide_label: true %>
      </div>
    </div>

    <br>

    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary" %>
      <% if params[:modal_enabled] != 'true' %>
          <%= link_to 'Cancel', sleeps_cancel_path, remote: true, class: "btn btn-default" %>
      <% else %>
          <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
      <% end %>
    </div>
<% end %>

app/views/sleeps/_index.html.erb
<% render "shared/set_lookback" %>

<%
   $capture_date = Time.zone.now.to_date
   todays_sleeps = Sleep.where(user_id: current_user.id, finish_time: (Time.zone.now.to_date.in_time_zone.at_beginning_of_day..Time.zone.now.to_date.in_time_zone.end_of_day))
%>

<div class="container">
  <div>
    <% if (@user == nil || @user.id == current_user.id) && todays_sleeps.count < MAX_SLEEP_ENTRIES %>
        <h1><%= current_user.first_name.to_s + " " + current_user.last_name.to_s %>
          <h1>
            <%= link_to 'Add a new Sleep Entry', new_sleep_path(modal_enabled: 'true'), remote: true, class: "btn btn-primary" %>
    <% else %>
        <% if @user == nil %>
            <% user = current_user %>
        <% else %>
            <% user = @user %>
        <% end %>
        <h1><%= user.first_name.to_s + " " + user.last_name.to_s %>
          <h1>
    <% end %>

    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Change View Period <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% if params.has_key?(:user_id) %>
            <li><%= link_to 'Last Year', user_sleeps_path(@user, sleep_lookback_period: 'last_year') %></li>
            <li><%= link_to 'Last Month', user_sleeps_path(@user, sleep_lookback_period: 'last_month') %></li>
            <li><%= link_to 'Last Week', user_sleeps_path(@user, sleep_lookback_period: 'last_week') %></li>
            <li><%= link_to 'This Week', user_sleeps_path(@user, sleep_lookback_period: 'week') %></li>
            <li><%= link_to 'This Month', user_sleeps_path(@user, sleep_lookback_period: 'month') %></li>
            <li><%= link_to 'This Year', user_sleeps_path(@user, sleep_lookback_period: 'year') %></li>
        <% else %>
            <li><%= link_to 'Last Year', sleeps_path(sleep_lookback_period: 'last_year') %></li>
            <li><%= link_to 'Last Month', sleeps_path(sleep_lookback_period: 'last_month') %></li>
            <li><%= link_to 'Last Week', sleeps_path(sleep_lookback_period: 'last_week') %></li>
            <li><%= link_to 'This Week', sleeps_path(sleep_lookback_period: 'week') %></li>
            <li><%= link_to 'This Month', sleeps_path(sleep_lookback_period: 'month') %></li>
            <li><%= link_to 'This Year', sleeps_path(sleep_lookback_period: 'year') %></li>
        <% end %>
      </ul>
    </div>

    <div>
      <%= render "shared/chart_sleep" %>
    </div>

    <div>
      <%= render "details" %>
    </div>
  </div>

app/views/sleeps/_new.html.erb
<div class="modal-header">
  <h1>New Sleep Entry</h1>
</div>

<%= render 'form' %>

app/views/sleeps/_save.js.erb
<% flash.each do |type, message| %>
$('#flash_messages').html("<%= escape_javascript(render :partial => 'shared/flash_notices' , :locals => { :flash => flash }) %>").slideDown(500).delay(3000).slideUp(500)
<% end %>

$("ul.errors").html("");
<% if @sleep.errors.any? %>
<% @sleep.errors.full_messages.each do |message| %>
$("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
<% end %>
<% else %>
$(".sleep-index").html("<%= escape_javascript(render 'index') %>");
$("#sleep-modal").modal("hide");

$(".shared-index").html("<%= escape_javascript(render 'shared/index') %>");

$(".capture-delorean").html("<%= escape_javascript(render 'capture/delorean') %>");
$(".capture-nav").html("<%= escape_javascript(render 'capture/nav/sleep') %>");
$(".capture-window").html("<%= escape_javascript(render 'capture/show/sleep') %>");
<% end %>

app/views/sleeps/cancel.js.erb
$(".capture-delorean").html("<%= escape_javascript(render 'capture/delorean') %>");
$(".capture-nav").html("<%= escape_javascript(render 'capture/nav/sleep') %>");
$(".capture-window").html("<%= escape_javascript(render 'capture/show/sleep') %>");

app/views/sleeps/delete.js.erb
$("#inner-sleep-modal").html("<%= escape_javascript(render 'delete') %>");
$("#sleep-modal").appendTo("body").modal("show");
$("#sleep-modal").css("z-index", "1500");

app/views/sleeps/edit.js.erb
<% if params[:modal_enabled] == 'true' %>
$("#inner-sleep-modal").html("<%= escape_javascript(render 'edit') %>");
$("#sleep-modal").appendTo("body").modal("show");
$("#sleep-modal").css("z-index", "1500");
<% else %>
$(".capture-delorean").html("<%= escape_javascript(render 'capture/delorean_disabled') %>");
$(".capture-nav").html("<%= escape_javascript(render 'capture/nav/sleep_disabled') %>");
$(".capture-window").html("<%= escape_javascript(render 'capture/new/sleep', :controller => 'sleeps', :action => 'edit', :@sleep => Sleep.find(params[:id]) ) %>");
<% end %>

app/views/sleeps/index.html.erb
<div class="sleep-index">
  <%= render "index" %>
</div>

<div id="sleep-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-sleep-modal" class="modal-content"></div>
  </div>
</div>

app/views/sleeps/new.js.erb
<% if params[:modal_enabled] == 'true' %>
$("#inner-sleep-modal").html("<%= escape_javascript(render 'new') %>");
$("#sleep-modal").appendTo("body").modal("show");
$("#sleep-modal").css("z-index", "1500");
<% else %>
$(".capture-delorean").html("<%= escape_javascript(render 'capture/delorean_disabled') %>");
$(".capture-nav").html("<%= escape_javascript(render 'capture/nav/sleep_disabled') %>");
$(".capture-window").html("<%= escape_javascript(render 'capture/new/sleep', :controller => 'sleeps', :action => 'new', :@sleep => Sleep.new ) %>");
<% end %>